export const PERSONALITY_OPTIONS = ["Friendly", "Playful", "Energetic", "Calm", "Social"];

export const CATEGORY_LABELS = { all: "ทั้งหมด", recipe: "สูตรอาหาร", place: "สถานที่ Pet Friendly", clinic: "Clinic", tips: "ทั่วไป", story: "Pet Story", event: "ทั่วไป", question: "ทั่วไป" };

export const BLOG_TITLES = {
  p2: "สูตรขนมตับไก่อบ ทำง่าย หมาชอบมาก", p3: "สวนสาธารณะใจกลางเมืองที่พาหมาไปวิ่งได้ทั้งวัน",
  p4: "คลินิกทำหมันแมวราคาดี บริการดี", p5: "5 วิธีฝึกลูกสุนัขให้ขับถ่ายเป็นที่",
  p7: "นัดรวมตัวหมาโกลเด้นสุดสัปดาห์นี้", p8: "หาหมอรักษาโรคผิวหนังแมว",
  p10: "ไอศกรีมกล้วยปลอดภัยสำหรับแมวหน้าร้อนนี้", p11: "คาเฟ่ที่พาน้องหมาเข้าไปนั่งด้วยกันได้",
  p13: "วิธีลดขนร่วงของโกลเด้นในหน้าร้อน", p14: "งาน Pet Expo สัปดาห์หน้า มีบูธตรวจสุขภาพฟรี",
  p16: "รีวิวคลินิกฉุกเฉิน 24 ชม.", p17: "แมวไม่กินอาหารเม็ดเลย ทำยังไงดี",
  p18: "ขนมปังฟักทองสำหรับหมาแพ้ง่าย",
};

export const MUTUAL_CANDIDATES = ["bruno", "milo"];

export function initialState() {
  return {
    screen: "login",
    isMobile: false,
    toast: null,
    users: [
      { id: "sarah", name: "Sarah Chen", color: "#E3402B", bio: "Dog mom x2. เดินเขาทุกสุดสัปดาห์", location: "Bangkok" },
      { id: "james", name: "James Lee", color: "#2B5468", bio: "Shiba dad. คลั่งกาแฟ", location: "Bangkok" },
      { id: "nan", name: "Nan Siriwan", color: "#C9863B", bio: "ทาสแมวมือใหม่", location: "Chiang Mai" },
      { id: "mike", name: "Mike Torres", color: "#7C9473", bio: "พาหมาไปทุกที่ที่ไปได้", location: "Bangkok" },
      { id: "kevin", name: "Kevin Park", color: "#B5566D", bio: "บ้านมีแมว 2 ตัว", location: "Bangkok" },
      { id: "aom", name: "Aom Supaporn", color: "#8B5FBF", bio: "ชอบทำขนมให้หมากิน", location: "Nonthaburi" },
      { id: "me", name: "", color: "#E3402B", bio: "", location: "", email: "", phone: "", memberSince: "" },
    ],
    pets: [
      { id: "luna", ownerId: "sarah", name: "LUNA", species: "Dog", breed: "Golden Retriever", age: 2, gender: "Female", size: "Large", personality: ["Friendly", "Playful", "Energetic"], bio: "ชอบวิ่งเล่นในสวนตอนเช้าและงีบตอนบ่าย", interests: ["Walks", "Park", "Fetch"], distance: 3, photo: "#E9C79A" },
      { id: "bruno", ownerId: "james", name: "BRUNO", species: "Dog", breed: "Golden Retriever Mix", age: 2, gender: "Male", size: "Large", personality: ["Friendly", "Playful", "Energetic"], bio: "พลังงานเยอะ ชอบเล่นลูกบอลทั้งวัน", interests: ["Fetch", "Swimming", "Treats"], distance: 3, photo: "#D9A15B" },
      { id: "milo", ownerId: "nan", name: "MILO", species: "Cat", breed: "Domestic Shorthair", age: 1, gender: "Male", size: "Small", personality: ["Calm", "Social"], bio: "ชอบมองนกออกไปนอกหน้าต่าง", interests: ["Naps", "Boxes"], distance: 5, photo: "#B0B0AE" },
      { id: "coco", ownerId: "mike", name: "COCO", species: "Dog", breed: "Toy Poodle", age: 3, gender: "Female", size: "Small", personality: ["Playful", "Social"], bio: "รักทุกคนที่เจอ ไม่ว่าคนหรือหมา", interests: ["Walks", "Cuddles"], distance: 2, photo: "#EDE0C8" },
      { id: "simba", ownerId: "kevin", name: "SIMBA", species: "Cat", breed: "Maine Coon", age: 4, gender: "Male", size: "Large", personality: ["Calm", "Friendly"], bio: "ตัวใหญ่แต่ใจดี", interests: ["Sunbathing"], distance: 6, photo: "#C7A374" },
      { id: "daisy", ownerId: "aom", name: "DAISY", species: "Dog", breed: "Beagle", age: 1, gender: "Female", size: "Medium", personality: ["Energetic", "Friendly"], bio: "จมูกไวมาก ชอบสำรวจ", interests: ["Sniffing", "Park", "Treats"], distance: 4, photo: "#D8B48A" },
      { id: "rocky", ownerId: "sarah", name: "ROCKY", species: "Dog", breed: "Bulldog", age: 5, gender: "Male", size: "Medium", personality: ["Calm", "Friendly"], bio: "ชอบนอนมากกว่าวิ่ง", interests: ["Naps", "Treats"], distance: 3, photo: "#A88B6A" },
      { id: "mochi", ownerId: "james", name: "MOCHI", species: "Dog", breed: "Shiba Inu", age: 2, gender: "Female", size: "Medium", personality: ["Playful", "Social"], bio: "เสียงดังนิดหน่อยแต่รักเจ้าของมาก", interests: ["Walks"], distance: 7, photo: "#D77B3F" },
      { id: "whiskers", ownerId: "nan", name: "WHISKERS", species: "Cat", breed: "British Shorthair", age: 3, gender: "Female", size: "Medium", personality: ["Calm"], bio: "เจ้าหญิงประจำบ้าน", interests: ["Naps", "Treats"], distance: 5, photo: "#9CA3A8" },
      { id: "buddy", ownerId: "mike", name: "BUDDY", species: "Dog", breed: "Labrador", age: 1, gender: "Male", size: "Large", personality: ["Energetic", "Playful", "Social"], bio: "ว่ายน้ำเก่งมาก", interests: ["Swimming", "Fetch", "Park"], distance: 2, photo: "#E3C08A" },
      { id: "coffee", ownerId: "kevin", name: "COFFEE", species: "Cat", breed: "Siamese", age: 2, gender: "Male", size: "Small", personality: ["Social"], bio: "ชอบคุยเสียงดัง", interests: ["Toys", "Windows"], distance: 6, photo: "#7D6A56" },
      { id: "pepper", ownerId: "aom", name: "PEPPER", species: "Dog", breed: "Mixed", age: 4, gender: "Female", size: "Medium", personality: ["Friendly", "Calm"], bio: "เก็บมาเลี้ยงตั้งแต่เด็ก ใจดีที่สุด", interests: ["Walks", "Cuddles"], distance: 4, photo: "#8A7A63" },
      { id: "leo", ownerId: "sarah", name: "LEO", species: "Cat", breed: "Bengal", age: 2, gender: "Male", size: "Medium", personality: ["Energetic"], bio: "กระโดดเก่ง ชอบไต่ที่สูง", interests: ["Climbing", "Toys"], distance: 3, photo: "#C99B5C" },
      { id: "bella", ownerId: "me", name: "BELLA", species: "Dog", breed: "Corgi", age: 2, gender: "Female", size: "Medium", weight: 11, personality: ["Playful", "Friendly", "Energetic"], bio: "ขาสั้นแต่วิ่งไม่หยุด", interests: ["Walks", "Park", "Fetch"], distance: 0, photo: "#D9A15B" },
      { id: "tom", ownerId: "me", name: "TOM", species: "Cat", breed: "Domestic Shorthair", age: 3, gender: "Male", size: "Medium", weight: 5, personality: ["Calm"], bio: "นอนวันละ 16 ชั่วโมง", interests: ["Naps", "Sunbathing"], distance: 0, photo: "#B0B0AE" },
    ],
    posts: [
      { id: "p1", category: "story", petId: "luna", authorId: "sarah", caption: "เช้านี้ Luna ตื่นมาวิ่งไล่ผีเสื้อในสวนตั้งแต่ 6 โมง", likes: 132, liked: false, saved: false, comments: [{ user: "James Lee", color: "#2B5468", text: "น่ารักมากก" }], time: "2h" },
      { id: "p2", category: "recipe", petId: null, authorId: "aom", caption: "สูตรขนมตับไก่อบ ทำง่าย หมาชอบมาก", likes: 88, liked: false, saved: false, comments: [], time: "4h" },
      { id: "p3", category: "place", petId: null, authorId: "kevin", caption: "สวนสาธารณะใจกลางเมืองที่พาหมาไปวิ่งได้ทั้งวัน (สวนลุมพินี)", likes: 64, liked: false, saved: false, comments: [], time: "5h" },
      { id: "p4", category: "clinic", petId: null, authorId: "nan", caption: "คลินิกที่ทำหมันแมวราคาดี บริการดีมาก", likes: 41, liked: false, saved: false, comments: [], time: "1d" },
      { id: "p5", category: "tips", petId: null, authorId: "mike", caption: "5 วิธีฝึกลูกสุนัขให้ขับถ่ายเป็นที่", likes: 210, liked: false, saved: false, comments: [], time: "1d" },
      { id: "p6", category: "story", petId: "bruno", authorId: "james", caption: "บรูโน่จับได้ว่าตัวเองอ้วนขึ้น 2 กิโล 555", likes: 97, liked: false, saved: false, comments: [], time: "1d" },
      { id: "p7", category: "event", petId: null, authorId: "sarah", caption: "นัดรวมตัวหมาโกลเด้นสุดสัปดาห์นี้ที่สวนลุม", likes: 56, liked: false, saved: false, comments: [], time: "2d" },
      { id: "p8", category: "question", petId: null, authorId: "aom", caption: "มีใครรู้จักหมอที่รักษาโรคผิวหนังแมวเก่งๆบ้างคะ", likes: 23, liked: false, saved: false, comments: [], time: "2d" },
      { id: "p9", category: "story", petId: "milo", authorId: "nan", caption: "ไมโล่ติดหน้าต่างทั้งวัน ดูนกจนลืมกินข้าว", likes: 145, liked: false, saved: false, comments: [], time: "2d" },
      { id: "p10", category: "recipe", petId: null, authorId: "kevin", caption: "ไอศกรีมกล้วยปลอดภัยสำหรับแมวหน้าร้อนนี้", likes: 76, liked: false, saved: false, comments: [], time: "3d" },
      { id: "p11", category: "place", petId: null, authorId: "mike", caption: "คาเฟ่ที่พาน้องหมาเข้าไปนั่งด้วยกันได้เต็มร้าน (Pet Cafe Ari)", likes: 112, liked: false, saved: false, comments: [], time: "3d" },
      { id: "p12", category: "story", petId: "coco", authorId: "mike", caption: "โคโค่ไปเดินเล่นวันแรกหลังผ่าตัด กลับมาสดใสมาก", likes: 88, liked: false, saved: false, comments: [], time: "3d" },
      { id: "p13", category: "tips", petId: null, authorId: "james", caption: "วิธีลดขนร่วงของโกลเด้นในหน้าร้อน", likes: 134, liked: false, saved: false, comments: [], time: "4d" },
      { id: "p14", category: "event", petId: null, authorId: "nan", caption: "งาน Pet Expo สัปดาห์หน้า มีบูธตรวจสุขภาพฟรี", likes: 203, liked: false, saved: false, comments: [], time: "5d" },
      { id: "p15", category: "story", petId: "simba", authorId: "kevin", caption: "ซิมบ้านอนขวางทางเดินทั้งบ้านอีกแล้ว", likes: 167, liked: false, saved: false, comments: [], time: "5d" },
      { id: "p16", category: "clinic", petId: null, authorId: "sarah", caption: "รีวิวคลินิกฉุกเฉิน 24 ชม. ที่ช่วยรุกกี้ไว้ได้ทันเวลา", likes: 59, liked: false, saved: false, comments: [], time: "6d" },
      { id: "p17", category: "question", petId: null, authorId: "kevin", caption: "แมวไม่กินอาหารเม็ดเลย มีใครมีทริคแนะนำไหม", likes: 31, liked: false, saved: false, comments: [], time: "6d" },
      { id: "p18", category: "recipe", petId: null, authorId: "aom", caption: "ขนมปังฟักทองสำหรับหมาแพ้ง่าย ไม่ใส่นมไม่ใส่ไข่", likes: 95, liked: false, saved: false, comments: [], time: "1w" },
    ],
    matches: [
      { id: "m1", petId: "coco", matchedAt: "2 วันก่อน", updatedAt: Date.now() - 2 * 86400000 + 3600000, messages: [
        { from: "them", text: "Hi! เห็นน้อง Bella แล้วน่ารักมากเลย", time: "10:02" },
        { from: "me", text: "ขอบคุณค่ะ! โคโค่ก็น่ารักมากๆ", time: "10:05" },
        { from: "them", text: "สุดสัปดาห์นี้ไปเดินเล่นที่สวนกันไหม", time: "10:07" }] },
      { id: "m2", petId: "simba", matchedAt: "2 วันก่อน", updatedAt: Date.now() - 2 * 86400000, messages: [
        { from: "them", text: "Tom ดูขี้เกียจเหมือนซิมบ้าเลย", time: "14:20" },
        { from: "me", text: "ใช่เลย นอนทั้งวัน", time: "14:23" }] },
      { id: "m3", petId: "daisy", matchedAt: "3 วันก่อน", updatedAt: Date.now() - 3 * 86400000, messages: [
        { from: "me", text: "Bella อยากเจอ Daisy จังเลย", time: "09:11" },
        { from: "them", text: "มาเจอกันเสาร์นี้ไหมคะ", time: "09:15" }] },
    ],
    notifications: [
      { id: "n1", type: "like", text: "Sarah Chen กดไลค์โพสต์ของคุณ", time: "10m", read: false },
      { id: "n2", type: "comment", text: "James Lee แสดงความเห็นในโพสต์ของคุณ", time: "1h", read: false },
      { id: "n3", type: "match", text: "คุณ Match กับ Coco แล้ว", time: "1d", read: true },
      { id: "n4", type: "message", text: "Mike Torres ส่งข้อความใหม่", time: "2d", read: true },
      { id: "n5", type: "interest", text: "มีคนสนใจ Bella", time: "3d", read: true },
      { id: "n6", type: "like", text: "Nan Siriwan กดไลค์โพสต์ของคุณ", time: "4d", read: true },
    ],
    openComments: [],
    commentDrafts: {},
    blockedUserIds: [],
    followingIds: ["sarah", "james"],
    suggestedUsers: [],
    passedPetIds: [],
    lastPassedId: null,
    interestedPetIds: [],
    feedFilter: { category: "all", species: "all", sort: "latest", search: "" },
    searchOpen: false,
    matchFilters: { species: "all", distance: "anywhere", gender: "any", size: "all", personality: [] },
    matchingPetId: null,
    matchingPurpose: "playmate",
    postDetailFrom: "explore",
    petProfileFrom: "myPets",
    userProfileFrom: "home",
    modals: { createPost: false, matchFilter: false, mutualMatch: false, reportUser: false, reportPost: false, block: false, logoutConfirm: false, deletePet: false, deletePost: false, editProfile: false },
    newMatchPetId: null,
    reportTargetType: null,
    reportTargetId: null,
    reportReason: "",
    blockTargetUserId: null,
    loginForm: { email: "", password: "" },
    registerForm: { name: "", email: "", password: "", confirm: "" },
    user: null,
    sessionReady: false,
    authPending: false,
    authError: null,
    petPending: false,
    profilePending: false,
    postPending: false,
    postForm: { caption: "", petId: "", category: "story", location: "", title: "" },
    postFormIsBlog: false,
    petForm: { id: null, name: "", species: "Dog", breed: "", age: "", gender: "Male", size: "Medium", personality: [], bio: "", interestsRaw: "" },
    fieldDropdownOpen: null,
    deletePetId: null,
    editingPostId: null,
    deletePostId: null,
    postMenuOpenId: null,
    profileForm: { name: "", location: "", bio: "", phone: "", email: "" },
    chatDraft: "",
  };
}
