-- Requires PostGIS for the geography column in "provinces".
CREATE EXTENSION IF NOT EXISTS postgis;

-- Custom enum for pet_rel.rel_type ('L' = Lover, 'F' = Friend).
-- Note: CREATE TYPE has no "IF NOT EXISTS" in PostgreSQL — if you re-run
-- this script against an existing database, DROP TYPE "rel_type_enum";
-- first, or wrap this in a DO block that checks pg_type.
CREATE TYPE "rel_type_enum" AS ENUM ('L', 'F');


CREATE TABLE IF NOT EXISTS "acc" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"email" VARCHAR(255) NOT NULL,
	"pwd" VARCHAR(255) NOT NULL,
	"date" TIMESTAMPTZ NOT NULL,
	"pict" VARCHAR(255),
	"phone" VARCHAR(255),
	"prov_id" INTEGER,
	"about" VARCHAR(255),
	PRIMARY KEY("id")
);


CREATE TABLE IF NOT EXISTS "provinces" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY,
	"prov" VARCHAR(255) UNIQUE NOT NULL,
	"point" GEOGRAPHY(Point, 4326) NOT NULL,
	PRIMARY KEY("id")
);


CREATE TABLE IF NOT EXISTS "acc_rel" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY,
	"acc_init" INTEGER NOT NULL,
	"acc_rec" INTEGER NOT NULL,
	"follow" BOOLEAN NOT NULL,
	"block" BOOLEAN NOT NULL,
	"report_id" INTEGER,
	PRIMARY KEY("id")
);


CREATE TABLE IF NOT EXISTS "acc_reports" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY,
	"report" VARCHAR(255) UNIQUE NOT NULL,
	PRIMARY KEY("id")
);


CREATE TABLE IF NOT EXISTS "pet_pro" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY,
	"pict" VARCHAR(255),
	"name" VARCHAR(255) NOT NULL,
	"spec_id" INTEGER,
	"sex_id" INTEGER,
	"size_id" INTEGER,
	"breed_id" INTEGER,
	"age" SMALLINT,
	"about" VARCHAR(255),
	"acc_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);


CREATE TABLE IF NOT EXISTS "pet_cha" (
	"pet_id" INTEGER NOT NULL,
	"cha_id" INTEGER NOT NULL,
	PRIMARY KEY("pet_id", "cha_id")
);


CREATE TABLE IF NOT EXISTS "cha" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY,
	"cha" VARCHAR(255) UNIQUE NOT NULL,
	PRIMARY KEY("id")
);


CREATE TABLE IF NOT EXISTS "pet_rel" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY,
	"pet_init" INTEGER NOT NULL,
	"pet_rec" INTEGER NOT NULL,
	"like" BOOLEAN NOT NULL,
	"rel_type" rel_type_enum NOT NULL,
	PRIMARY KEY("id")
);


CREATE TABLE IF NOT EXISTS "species" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY,
	"spec" VARCHAR(255) UNIQUE NOT NULL,
	PRIMARY KEY("id")
);


CREATE TABLE IF NOT EXISTS "sexes" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY,
	"sex" VARCHAR(255) UNIQUE NOT NULL,
	PRIMARY KEY("id")
);


CREATE TABLE IF NOT EXISTS "sizes" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY,
	"size" VARCHAR(255) UNIQUE NOT NULL,
	PRIMARY KEY("id")
);


CREATE TABLE IF NOT EXISTS "h_post" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY,
	"pict" VARCHAR(255),
	"cont" TEXT NOT NULL,
	"pet_id" INTEGER,
	"acc_id" INTEGER NOT NULL,
	"date" TIMESTAMPTZ NOT NULL,
	PRIMARY KEY("id")
);


CREATE TABLE IF NOT EXISTS "h_post_rel" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY,
	"acc_id" INTEGER NOT NULL,
	"h_post_id" INTEGER NOT NULL,
	"report_id" INTEGER,
	"like" BOOLEAN NOT NULL,
	"save" BOOLEAN NOT NULL,
	PRIMARY KEY("id")
);


CREATE TABLE IF NOT EXISTS "h_post_com" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY,
	"acc_id" INTEGER NOT NULL,
	"h_post_id" INTEGER NOT NULL,
	"mess" TEXT NOT NULL,
	"date" TIMESTAMPTZ NOT NULL,
	PRIMARY KEY("id")
);


CREATE TABLE IF NOT EXISTS "x_post" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY,
	"pict" VARCHAR(255),
	"title" VARCHAR(255),
	"cont" TEXT NOT NULL,
	"pet_id" INTEGER,
	"topic_id" INTEGER NOT NULL,
	"spec_id" INTEGER,
	"acc_id" INTEGER NOT NULL,
	"date" TIMESTAMPTZ NOT NULL,
	PRIMARY KEY("id")
);


CREATE TABLE IF NOT EXISTS "x_post_topics" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY,
	"topic" VARCHAR(255) UNIQUE NOT NULL,
	PRIMARY KEY("id")
);


CREATE TABLE IF NOT EXISTS "x_post_rel" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY,
	"acc_id" INTEGER NOT NULL,
	"x_post_id" INTEGER NOT NULL,
	"report_id" INTEGER,
	"like" BOOLEAN NOT NULL,
	"save" BOOLEAN NOT NULL,
	PRIMARY KEY("id")
);


CREATE TABLE IF NOT EXISTS "x_post_com" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY,
	"acc_id" INTEGER NOT NULL,
	"x_post_id" INTEGER NOT NULL,
	"mess" TEXT NOT NULL,
	"date" TIMESTAMPTZ NOT NULL,
	PRIMARY KEY("id")
);


CREATE TABLE IF NOT EXISTS "post_reports" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY,
	"report" VARCHAR(255) UNIQUE NOT NULL,
	PRIMARY KEY("id")
);


CREATE TABLE IF NOT EXISTS "messages" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY,
	"acc_sen" INTEGER NOT NULL,
	"acc_rec" INTEGER NOT NULL,
	"mess" TEXT NOT NULL,
	"date" TIMESTAMPTZ NOT NULL,
	PRIMARY KEY("id")
);


CREATE TABLE IF NOT EXISTS "breeds" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY,
	"spec_id" INTEGER,
	"breed" VARCHAR(255) UNIQUE NOT NULL,
	PRIMARY KEY("id")
);


ALTER TABLE "pet_pro"
ADD FOREIGN KEY("acc_id") REFERENCES "acc"("id")
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "h_post"
ADD FOREIGN KEY("acc_id") REFERENCES "acc"("id")
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "x_post"
ADD FOREIGN KEY("acc_id") REFERENCES "acc"("id")
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "h_post_rel"
ADD FOREIGN KEY("acc_id") REFERENCES "acc"("id")
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "h_post_com"
ADD FOREIGN KEY("acc_id") REFERENCES "acc"("id")
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "acc_rel"
ADD FOREIGN KEY("acc_init") REFERENCES "acc"("id")
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "acc_rel"
ADD FOREIGN KEY("acc_rec") REFERENCES "acc"("id")
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "messages"
ADD FOREIGN KEY("acc_sen") REFERENCES "acc"("id")
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "messages"
ADD FOREIGN KEY("acc_rec") REFERENCES "acc"("id")
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "x_post_rel"
ADD FOREIGN KEY("acc_id") REFERENCES "acc"("id")
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "x_post_com"
ADD FOREIGN KEY("acc_id") REFERENCES "acc"("id")
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "acc"
ADD FOREIGN KEY("prov_id") REFERENCES "provinces"("id")
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "pet_cha"
ADD FOREIGN KEY("pet_id") REFERENCES "pet_pro"("id")
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "pet_cha"
ADD FOREIGN KEY("cha_id") REFERENCES "cha"("id")
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "pet_pro"
ADD FOREIGN KEY("spec_id") REFERENCES "species"("id")
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "pet_pro"
ADD FOREIGN KEY("sex_id") REFERENCES "sexes"("id")
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "pet_pro"
ADD FOREIGN KEY("size_id") REFERENCES "sizes"("id")
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "x_post_com"
ADD FOREIGN KEY("x_post_id") REFERENCES "x_post"("id")
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "x_post_rel"
ADD FOREIGN KEY("x_post_id") REFERENCES "x_post"("id")
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "x_post_rel"
ADD FOREIGN KEY("report_id") REFERENCES "post_reports"("id")
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "acc_rel"
ADD FOREIGN KEY("report_id") REFERENCES "acc_reports"("id")
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "h_post_rel"
ADD FOREIGN KEY("h_post_id") REFERENCES "h_post"("id")
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "h_post_rel"
ADD FOREIGN KEY("report_id") REFERENCES "post_reports"("id")
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "x_post"
ADD FOREIGN KEY("pet_id") REFERENCES "pet_pro"("id")
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "x_post"
ADD FOREIGN KEY("topic_id") REFERENCES "x_post_topics"("id")
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "x_post"
ADD FOREIGN KEY("spec_id") REFERENCES "species"("id")
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "h_post"
ADD FOREIGN KEY("pet_id") REFERENCES "pet_pro"("id")
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "h_post_com"
ADD FOREIGN KEY("h_post_id") REFERENCES "h_post"("id")
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "pet_rel"
ADD FOREIGN KEY("pet_init") REFERENCES "pet_pro"("id")
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "pet_rel"
ADD FOREIGN KEY("pet_rec") REFERENCES "pet_pro"("id")
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "pet_pro"
ADD FOREIGN KEY("breed_id") REFERENCES "breeds"("id")
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "breeds"
ADD FOREIGN KEY("spec_id") REFERENCES "species"("id")
ON DELETE NO ACTION ON UPDATE NO ACTION;